### ISSUE TITLE
Alert Policies API is Depreceted

### ISSUE THREAD

**Issue by amirkav** [ambitioninc/newrelic-api#31]
Hi,

When I follow the docs to get alert policies, I get the following error:

Traceback (most recent call last):
  File ".../newrelic_api/alert_policies.py", line 95, in list
    params=self.build_param_string(filters)
  File ".../newrelic_api/base.py", line 47, in _get
    raise NewRelicAPIServerException('{}: {}'.format(response.status_code, response.text))
NewRelicAPIServerException: 410: {"error":{"title":"**The alert policies API is deprecated. Please see 'alerts.newrelic.com' for the new alerting infrastructure.**"}}

Any idea why this is happening? When I test the GET query on New Relic's API Explorer or when I use Perl to import the data, I don't have any problems. 
Maybe there is something wrong with the way the header parameters are created?

**Comment by caseybecking** [comment]
Couple things need to be updated to make this work - 

`alert_policies` 
Needs to be changed to 
`alerts_policies`

And for the response on it 
`marketing_policy = AlertPolicies().list(
    filter_name='Marketing Policy',
    filter_type=['application'],
    filter_enabled=True
)['alert_policies'][0]`

Would become 

`marketing_policy = AlertPolicies().list(
    filter_name='Marketing Policy',
    filter_type=['application'],
    filter_enabled=True
)['policies'][0]`

**Comment by caseybecking** [comment]
I can send a PR not sure what else it would need?

**Comment by caseybecking** [comment]
And looks like I spoke to soon a PR has already been submitted - 
https://github.com/ambitioninc/newrelic-api/pull/29
